#########################
#####   LumberJack  #####
#########################

#
# LumberJack provides the /lumberjack command, that toggles
# tree gravity per player. Players need the lumberjack.use permission.
# When a player has the lumberjack.force permission, they cannot
# disable tree gravity.
#
# Aliases for /lumberjack:
# - /treegravity
# - /gravity
# - /tg
#

# Whether gravity is enabled by default for new players
# Hint: To force players using gravity, give them
# the lumberjack.force permission
gravity-enabled-by-default: false

# When enabled, tree gravity will only apply when the
# player used an axe to break the log.
must-use-axe: true

# When "must-use-axe" is enabled, players have to use at least this
# kind of axe for tree gravity. E.g. when set to DIAMOND, tree
# gravity only works for diamond and netherite axes. When set to
# WOOD, it works with all axes.
requires-at-least: WOOD

# When enabled, tree gravity will only work when the
# player is sneaking
must-sneak: false

# When enabled, leaves will decay within the given duration
fast-leaves-decay: false

# The amount of seconds it takes at most to have leaves decay.
fast-leaves-decay-duration: 10

# Only adjust this when you experience lag using custom world
# generators
max-decay-tasks: 1000

# When true, only naturally generated (world generation or via sapling) trees will have gravity
# When false, logs placed by players will also have gravity
only-natural-logs: true

# Whether logs attached at the side or diagonally of the tree trunk
# should also fall down
attached-logs-fall-down: true

# Prevents the placement of torches or other blocks
# inside or under falling logs.
# Also prevents the logs from starting to fall down
# when the first block below the log (except air)
# is not solid.
prevent-torch-exploit: true

# Maximum number of air blocks that can be inside the tree trunk
# If more than the specificied number of air blocks are present inside the trunk,
# it will not be counted as a tree
max-air-in-trunk: 1

# Prevents falling logs from dropping into items if the
# player somehow manages to bypass the torch exploit
# prevention.
prevent-torch-exploit-aggressive: false

# when set to true, players with gravity DISABLED will be
# shown a message on how to enable tree gravity
# when they break a log for the first time.
# consider setting this to true when you disable gravity by default.
# see also -> message-when-breaking-log
show-message-when-breaking-log: true

# when set to true, players with gravity ENABLED will be
# shown a message on how to disable tree gravity
# when they break a log for the first time.
# consider setting this to true when you enable gravity by default.
# see also -> message-when-breaking-log2
show-message-when-breaking-log-and-gravity-is-enabled: false

# when set to true, the messages are shown again when a player
# logs out and back in and then breaks a log again.
show-message-again-after-logout: true

# when set to true, player settings will be stored inside the Player's PDC.
# when set to false, player settings will be stored in per-player yaml files.
use-pdc: true

#########################
#### disabled worlds ####
#########################

# You can disable LumberJack for certain worlds. Each world's name has to
# be on a separate line, starting with a hyphen and followed by a space

# Example:
#
# disabled-worlds:
# - world_nether
# - world_the_end

disabled-worlds:

#########################
##### localization ######
#########################

##### English
message-gravity-enabled: "<gray>Tree gravity has been <green>enabled<gray>."
message-gravity-disabled: "<gray>Tree gravity has been <red>disabled<gray>."
message-when-breaking-log: "<gray>Hint: Type <gold>/lumberjack<gray> to enable tree gravity."
message-when-breaking-log2: "<gray>Hint: Type <gold>/lumberjack<gray> to disable tree gravity."
message-can-not-disable: "<red>You are not allowed to disable tree gravity."

##### Bulgarian
#message-gravity-enabled: "<gray>Дървестната гравитация беше <green>активирана<gray>."
#message-gravity-disabled: "<gray>Дървестната гравитация беше <red>деактивирана<gray>."
#message-when-breaking-log: "<gray>Подсказка: Напишете <gold>/lumberjack<gray>, за да активирате дървестната гравитация."
#message-when-breaking-log2: "<gray>Подсказка: Напишете <gold>/lumberjack<gray>, за да деактивирате дървестната гравитация."
#message-can-not-disable: "<red>Не Ви е позволено да изключвате дървестната гравитация."

##### Dutch
#message-gravity-enabled: "<gray>Boom zwaartekracht is <green>ingeschakeld<gray>."
#message-gravity-disabled: "<gray>Boom zwaartekracht is <red>uitgeschakeld<gray>."
#message-when-breaking-log: "<gray>Hint: Type <gold>/lumberjack<gray> om boom zwaartekracht in te schakelen."
#message-when-breaking-log2: "<gray>Hint: Type <gold>/lumberjack<gray> om boom zwaartekracht uit te schakelen."
#message-can-not-disable: "<red>Je bent niet toegestaan om boom zwaartekracht uit te schakelen."

##### French
#message-gravity-enabled: "<gray>La gravité d'arbre a été <green>activée<gray>."
#message-gravity-disabled: "<gray>La gravité d'arbre a été <red>désactivée<gray>."
#message-when-breaking-log: "<gray>Astuce: écris <gold>/lumberjack<gray> pour activer la gravité d'arbre."
#message-when-breaking-log2: "<gray>Astuce: écris <gold>/lumberjack<gray> pour désactiver la gravité d'arbre."
#message-can-not-disable: "<red>Vous n'avez pas la permission de désactiver la gravité d'arbre."

##### Hungarian
# message-gravity-enabled: "<gray>A fa gravitációja <green>engedélyezve<gray> lett."
# message-gravity-disabled: "<gray>A fa gravitációja le lett <red>tiltva<gray>."
# message-when-breaking-log: "<gray>Tipp: Írd be a <gold>/lumberjack<gray> parancsot, hogy engedélyezd a fa gravitációját."
# message-when-breaking-log2: "<gray>Tipp: Írd be a <gold>/lumberjack<gray> parancsot, hogy letiltsd a fa gravitációját."
# message-can-not-disable: "<red>Neked nem engedélyezett, hogy letiltsd a fa gravitációját."

##### Polish
#message-gravity-enabled: "<gray>Grawitacja drzew została <green>włączona<gray>."
#message-gravity-disabled: "<gray>Grawitacja drzew została <red>wyłączona<gray>."
#message-when-breaking-log: "<gray>Podpowiedź: Wpisz <gold>/lumberjack<gray> aby włączyć grawitację drzew."
#message-when-breaking-log2: "<gray>Podpowiedź: Wpisz <gold>/lumberjack<gray> aby wyłączyć grawitację drzew."
#message-can-not-disable: "<red>Nie możesz wyłączyć grawitacji drzew."

##### Romanian
#message-gravity-enabled: "<gray>Graviația copacilor a fost <green>activată<gray>."
#message-gravity-disabled: "<gray>Graviația copacilor a fost <red>dezactivată<gray>."
#message-when-breaking-log: "<gray>Sfat: Scrie <gold>/lumberjack<gray> pentru a activa gravitația copacilor."
#message-when-breaking-log2: "<gray>Sfat: Scrie <gold>/lumberjack<gray> pentru a dezactiva gravitația copacilor."
#message-can-not-disable: "<red>Nu ai permisiunea să dezactivezi gravitația copacilor."

##### Russian
#message-gravity-enabled: "<gray>Гравитация для деревьев <green>включена<gray>."
#message-gravity-disabled: "<gray>Гравитация для деревьев <red>отключена<gray>."
#message-when-breaking-log: "<gray>Подсказка: Введите <gold>/lumberjack<gray>, чтобы включить гравитацию для деревьев."
#message-when-breaking-log2: "<gray>Подсказка: Введите <gold>/lumberjack<gray>, чтобы отключить гравитацию для деревьев."
#message-can-not-disable: "<red>Вы не можете отключить гравитацию для деревьев."

##### Spanish
#message-gravity-enabled: "<gray>La gravedad de arboles ha sido <green>habilitada<gray>."
#message-gravity-disabled: "<gray>La gravedad de arboles ha sido <red>deshabilitada<gray>."
#message-when-breaking-log: "<gray>Lumberjack: Utiliza <gold>/lumberjack<gray> para habilitar la gravedad de arboles."
#message-when-breaking-log2: "<gray>Lumberjack: Utiliza <gold>/lumberjack<gray> para deshabilitar la gravedad de arboles."
#message-can-not-disable: "<red>No tienes permitido deshabilitar la gravedad de arboles."

##### Swedish
#message-gravity-enabled: "<gray>Trädgravitation har <green>aktiverats<gray>."
#message-gravity-disabled: "<gray>Trädgravitationen har <red>inaktiverats<gray>."
#message-when-breaking-log: "<gray>Tips: Skriv <gold>/lumberjack<gray> för att aktivera trädgravitation."
#message-when-breaking-log2: "<gray>Tips: Skriv <gold>/lumberjack<gray> för att inaktivera trädgravitationen."
#message-can-not-disable: "<red>Du får inte inaktivera trädgravitationen."

##### Turkish
#message-gravity-enabled: "<gray>Ağaç yerçekimi <green>aktifleştirildi<gray>."
#message-gravity-disabled: "<gray>Ağaç yerçekimi <red>deaktifleştirildi<gray>."
#message-when-breaking-log: "<gray>İpucu: Ağaç yerçekimini aktifleştirmek için <gold>/lumberjack<gray> yazınız."
#message-when-breaking-log2: "<gray>İpucu: Ağaç yerçekimini deaktifleştirmek için <gold>/lumberjack<gray> yazınız."
#message-can-not-disable: "<red>Ağaç yerçekimini deaktifleştirmek için yetkiniz yok."


#########################
#####     Done!     #####
#########################

# please do not change the following line manually!
config-version: 14
